return {
	name = "Control Relay",
	category = "Infrastructure",
	description = "Extends the control zone when reachable from Nexus via data network.",
	attributes = {
		type = {
			title = "Type",
			inspector = { readonly = true },
			description = "",
			type = AttributeType.STRING,
			value = "Control Relay",
		},
		stable = {
			title = "Stable",
			description = "If browned out, automatically starts again when the grid can supply it",
			type = AttributeType.BOOL,
			value = true,
		},
		temp_proof = {
			title = "Temp Proof",
			description = "Does not overheat or freeze",
			type = AttributeType.BOOL,
			value = true,
		},
		control_radius = {
			title = "Control Radius",
			description = "Placement and visibility radius in grid cells",
			type = AttributeType.INT,
			value = 15,
		},
		heartbeat_interval = {
			title = "Heartbeat Interval",
			description = "Ticks between heartbeat packets",
			type = AttributeType.INT,
			value = 60,
		},
		target = {
			title = "Target data connector",
			description = "Component id of data connector used for sending heartbeat packets",
			type = AttributeType.INT,
			value = -1,
			inspector = { widget = "link", link_scope = "frame", link_filter = "Data Connector" },
		},
		consumption = {
			title = "Consumption",
			description = "Power consumption per scan",
			type = AttributeType.FLOAT,
			value = 100.0,
		},
		link_status = {
			title = "Nexus link",
			description = "Data path and heartbeat registration (updated by engine)",
			type = AttributeType.STRING,
			value = "—",
			inspector = { readonly = true },
		},
	},
	state = ComponentState.DEACTIVATED,
	size = ComponentSize.S,
	require = { "Core" },
	api = {},
}
