return {
	name = "Nexus",
	category = "Unique",
	description = "Starting component",
	attributes = {
		type = {
			title = "Type",
			description = "",
			type = AttributeType.STRING,
			value = "Nexus",
		},
		stable = {
			title = "Stable",
			description = "Does continue work after power loss",
			type = AttributeType.BOOL,
			value = true,
		},
		production = {
			title = "Production",
			description = "Power production",
			type = AttributeType.FLOAT,
			value = 1000.0,
			easing = {
				type = AttributeEasingType.JITTER,
				range = 0.05,
				period = 1000.0,
			},
		},
		slots = {
			title = "Slots",
			description = "Number of slots",
			type = AttributeType.INT,
			value = 1,
		},
		temp_proof = {
			title = "Temp Proof",
			description = "Does not overheat or freeze",
			type = AttributeType.BOOL,
			value = true,
		},
		target = {
			title = "Target storage",
			description = "Component id of storage that absorbs spendable items into the global pool",
			type = AttributeType.INT,
			value = -1,
			target_filter = "Storage",
		},
		target_data = {
			title = "Target data connector",
			description = "Component id of data connector used for control zone heartbeat reception",
			type = AttributeType.INT,
			value = -1,
			target_filter = "Data Connector",
		},
		control_radius = {
			title = "Control Radius",
			description = "Placement and visibility radius in grid cells",
			type = AttributeType.INT,
			value = 10,
		},
		alive_relays = {
			title = "Alive Relays",
			description = "Comma-separated frame IDs of reachable control relays (managed by blueprint code)",
			type = AttributeType.STRING,
			value = "",
		},
	},
	state = ComponentState.ACTIVE,
	size = ComponentSize.L,
	api = {},
}
